# 执行： docker compose -p directus-client up -d
# 上述命令意思为：项目命名为directus-client，启动容器并后台运行

# 项目默认名称是项目所在文件夹的名称。

# 每次执行，都会重新读取.env文件中的环境变量，并覆盖原有值。
# 但是请注意，nuxt项目的生产环境不会受到.env文件中环境变量的影响。
# 如果想在生产环境中设置环境变量，请使用终端将环境变量作为参数传递，例如：
# $ DATABASE_HOST=mydatabaseconnectionstring node .output/server/index.mjs

# docker compose up的时候，如果设置了env_file，则会自动读取.env文件中的环境变量。

# 参考：https://nuxtjs.org.cn/docs/guide/directory-structure/env

services:

  directus-client:
    image: skydtrtzmr/my-directus-client:latest
    ports:
      - 3001:3000
    env_file:
      - .env
  redis-container:
    image: redis:6
    ports:
      - 6379:6379